### ISSUE TITLE
can you help me with this adjustment in picks and bans?

### ISSUE THREAD

**Issue by overkido** [Sky-CSC/OSL#18]
I tried to put it but it doesn't take this adjustment in the css in the view3 settings, I couldn't put it can you help me or make these adjustments, and do you have any prediction of when the next update comes out?

![image](https://github.com/Sky-CSC/OSL/assets/89580284/e6ed018b-a1e9-4465-a19c-71e15a39f6f2)

**Comment by Sky-CSC** [comment]
Have you tried editing this -> [view3](https://github.com/Sky-CSC/OSL/blob/main/OSL-Web/Pages/ChampSelect/ChampSelectView3Page.razor.css) ?
I don't have much time at the moment, but at the latest a version will be released in early October. I'll try for the end of August to release the version (1.2.0) with the display of objects, level, drake, ... #15 . 
For October, I'll try to cover issues #13 #14 #17

**Comment by overkido** [comment]
I already tried to edit it through the css because the view3 link does not save the configuration, every time you run the app again you have to configure the entire color table, another topic where I can change the text font?

**Comment by Sky-CSC** [comment]
You need to generate the configuration file in "Config" and if you want to change the default display file change it on /OSL-Web/Configuration/Overlay/ChampSelect/View3/default.json
![image](https://github.com/Sky-CSC/OSL/assets/46931832/84552ff3-19d3-44bd-9ac4-c284733cda80)

For the font, you need to add a file in the font directory /OSL/tree/main/OSL-Web/wwwroot/css/font/ and change the path in the css file
```css
/*##########################################################*/
/*######################## General #########################*/
/*##########################################################*/

@font-face {
    font-family: MyFont;
    src: url(../css/font/fonts/fontLoL.ttf);
}
```
Automated font changes are not currently planned (like colors)
